on: [push, workflow_dispatch]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows
            os: windows-latest
          - name: Linux
            os: ubuntu-latest
          - name: Darwin
            os: macos-latest
    runs-on: ${{ matrix.os }} 
    name: ${{ matrix.name }} 
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        id: test1
        with:
          cmd: |
            systemd-analyze blame
            sudo lsblk
            sleep 5
            grep MemTotal /proc/meminfo
            echo "First test"
          filesize: 20G
          memory: 6G
          host-cmd: |
            wsl-bash -c "df -h"
          debug: true
      - uses: ./
        id: test2
        with:
          cmd: |
            echo "Second test"
          image-path: /mnt/nixos.qcow2
      - uses: ./
        id: test3
        with:
          cmd: |
            echo "Third test"
          filesize: 30G
          image-path: ${{ steps.test2.outputs.image-path }}
