on: [push, workflow_dispatch]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows
            os: windows-latest
          - name: Linux
            os: ubuntu-latest
          - name: Darwin
            os: macos-latest
    runs-on: ${{ matrix.os }} 
    name: ${{ matrix.name }} 
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        id: test1
        with:
          cmd: |
            sudo lsblk
            sleep 5
            grep MemTotal /proc/meminfo
          filesize: 20G
          memory: 6G
          host-cmd: |
            df -h
          debug: true
      - uses: ./
        id: test2
        with:
          cmd: |
            echo "second test"
          host-cmd: |
            df -h
          img-path: ${{ github.workspace }}/nixos.qcow2
      - uses: ./
        id: test3
        with:
          cmd: |
            echo "second test"
          img-path: ${{ steps.test2.outputs.image-path }}
